### ISSUE TITLE
Parameter map_width not working

### ISSUE THREAD

**Issue by laurelstreng** [cmanon/wp-strava#24]
Testing out your latest version of the plugin and setting a route to `map_height=640px` worked great, but when i tried also setting a width such as `map_width=1100px` it didn't seem to work at all?

Example of my use case:
[route id=17190262 image_only=true map_width=1065px map_height=450px]

**Comment by jrfoell** [comment]
Thank you - I'm working on this today, hopefully it's a quick fix!

**Comment by jrfoell** [comment]
I looked at this and it was puzzling, but I found the answer. Static map images are limited to 640x640 unless you're on a premium API plan: https://developers.google.com/maps/documentation/maps-static/dev-guide#Imagesizes

I'd like to investigate the possibility of an alternate mapping solution which isn't as restrictive, but I won't have time to do that today, so I logged a new issue #26.
