### ISSUE TITLE
Investigate alternative mapping options to Google Maps

### ISSUE THREAD

**Issue by jrfoell** [cmanon/wp-strava#26]
Google Maps has several limitations including size: https://developers.google.com/maps/documentation/maps-static/dev-guide#Imagesizes

With the latest API changes and possible cost increases, we should look at some alternatives.

Currently leaning towards MapBox & Leaflet as that's what Strava is using. Branch for this work: https://github.com/cmanon/wp-strava/tree/feature/26-alt-maps-leaflet

**Comment by jrfoell** [comment]
One option suggested would to be to add a scale=2 option to the static map request

https://wordpress.org/support/topic/possible-to-add-scale-to-allow-for-1280x1280-images/

https://developers.google.com/maps/documentation/maps-static/dev-guide#Imagesizes

**Comment by cmanon** [comment]
I just can't remember how the maps were implemented, but there are several alternatives to Google Maps like Mapbox (even Strava switched to Mapbox) or OpenStreetMaps and several others that can be used if we implement the map functionality using [LeafletJS](https://leafletjs.com/). Will see if I can spare sometime to look into this one.

**Comment by jrfoell** [comment]
Suggestion to use `OpenLayer` https://wordpress.org/support/topic/add-google-map-alternative/

**Comment by jrfoell** [comment]
Suggestion to use Leaflet https://wordpress.org/support/topic/sorry-this-content-could-not-be-embedded-5/#post-14906962

**Comment by RonnyM82** [comment]
Hey guys, 

I'm not a good enough developer to help with coding, but I'd love to use this plugin on my running clubs website without the risk of Google hammering my credit card. Is there anything I could do to help this along?

**Comment by jrfoell** [comment]
I actually have a working prototype using MapBox's static maps API - hoping to release it before the end of the year. Keep in mind MapBox has a similar terms of service as google (https://www.mapbox.com/pricing/#glstatic - 50k requests are free per month), but they don't require you to add a credit card to your account like google does.

**Comment by RonnyM82** [comment]
Legend. Thanks. And yeah I think that would work better for the club. We don't expect much traffic 🙂
