### ISSUE TITLE
Show Activity Description?

### ISSUE THREAD

**Issue by einzelfabrik** [cmanon/wp-strava#64]
Hello, is it possible to access the activity description? This using a shortcode would be great. I would like to include my descriptions of the activities written in Strava.

**Comment by einzelfabrik** [comment]
Today I have studied the API of Strava - it seems to be quite simple: When calling the Activity: https://www.strava.com/api/v3/activities/:id there is a record in the array: "description" - you would only have to evaluate it in the ActivityRenderer.php Is this simply possible?
![Uploading id.jpg…]()

**Comment by jrfoell** [comment]
Absolutely @einzelfabrik should it go below the map like an image caption?

**Comment by einzelfabrik** [comment]
Thanks for your answer - yes under the map would be a possibility, or above - or you can keep it dynamic and maybe use a shortcode?
