### ISSUE TITLE
Beta-1: can't view map widget due to PHP error

### ISSUE THREAD

**Issue by lancewillett** [cmanon/wp-strava#7]
#### Steps to repeat

1. Update to https://github.com/cmanon/wp-strava/releases/tag/v1.2.0-beta1
2. Add a new Map widget
3. Try to view the widget on the site's front-end

<img width="328" alt="screen shot 2017-10-26 at 11 15 35" src="https://user-images.githubusercontent.com/66797/32069824-297a2068-ba3f-11e7-9303-4632f7f15991.png">

#### What I expected to happen

To see the map widget

<img width="348" alt="screen shot 2017-10-26 at 11 07 05" src="https://user-images.githubusercontent.com/66797/32069813-23ce2ce0-ba3f-11e7-8e21-d0ccf595ac24.png">

#### What actually happened

No map widget, but I do see a PHP warning with debug turned on.

```
NOTICE: wp-content/plugins/wp-strava/lib/LatestMapWidget.class.php:67 - Undefined index: distance_min
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/p2-breathe/index.php'), get_sidebar, locate_template, load_template, require_once('/themes/p2-breathe/sidebar.php'), dynamic_sidebar, call_user_func_array, WP_Widget->display_callback, WPStrava_LatestMapWidget->widget
```

**Comment by jrfoell** [comment]
Thanks @lancewillett! I committed a change today that squashes the undefined index issue.
